name: news
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  vexana: ^3.4.1
  nb_utils: ^4.6.22
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  kartal: ^2.8.0
  build_runner: ^2.4.4
  url_launcher: ^6.1.11
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/